name: CI (Android)

# Trigger this workflow on push or pull request
on: push

env:
  SRC_DIR_PATH: desktop_version

jobs:
  build-android:
    name: Build (Android)

	only:
		- web

    runs-on: ubuntu-18.04

    env:
      VVVVVV_CE_ANDROID_BUILD: 1

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache data.zip
      uses: actions/cache@v1
      with:
        path: .github/resources/data-zip
        key: data-zip-folder

    - name: Cache CMake
      uses: actions/cache@v1
      with:
        path: .github/resources/cmake
        key: cmake-3-16-4-resources

    - name: Install pinned CMake
      run: ${SRC_DIR_PATH}/pinned-cmake.sh

    - name: Install dependencies
      run: sudo apt-get install -y ninja-build tree

    - name: Copy data.zip
      run: |
          cd .github/resources/
          ../../desktop_version/download-data.sh
          (cd ../../desktop_version/data && zip -r ../../.github/resources/data-zip/data.zip graphics/)
          mkdir -p ../../${SRC_DIR_PATH}/android-project/app/src/main/assets/
          cp -v data-zip/data.zip ../../${SRC_DIR_PATH}/android-project/app/src/main/assets/data.zip

    - name: Show project before build
      run: tree ${SRC_DIR_PATH}/android-project

    - name: Build
      run: cd ${SRC_DIR_PATH} && ./build.sh
      env:
        V6CORD_RELEASE: ${{ secrets.V6CORD_RELEASE }}
        V6CORD_RELEASE_PASSWORD: ${{ secrets.V6CORD_RELEASE_PASSWORD }}

    - name: Show project after build
      run: tree ${SRC_DIR_PATH}/android-project

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: VVVVVV-CE-Android
        path: desktop_version/android-project/app/build/outputs/apk
